### PR TITLE
Brackets Dracula Theme

### PR DESCRIPTION
**Pull request by felipekm**
Disclamer
--
- The CSS classes are stored in `theme.css`.
- The project has gulp as dependency that generates the `.zip` file containing `theme.css`, `package.json` with its default task.
- Installation instructions located in [README](https://github.com/dracula/brackets/blob/master/README.md).
- The ZIP file is necessary to upload it to the [Brackets Extension Directory](https://brackets-registry.aboutweb.com/).

I already uploaded it, anything let me know. 🤙 

image

### CODE REVIEW

**Comment by zenorocha** [comment]
Awesome work @felipekm!

Here are some questions and suggestions.

1. Do you really need to zip the files? Have you thought about using the zip file that GitHub releases generates?
2. If a custom zipping is really necessary, I'd suggest using [bestzip](https://www.npmjs.com/package/bestzip) inside your npm scripts. That way Gulp is one less dependency for people to install it.
3. I noticed you add a CHANGELOG file. We usually use GitHub releases for all Dracula repositories. Is there any reason you prefer the CHANGELOG file?
4. For the project name, I'd suggest using `Dracula Official` like VSCode did (https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula). I'll try to reach out to that other author and see if we can get the regular name.

I guess that's it for now, thanks a lot for your contribution!

**Comment by felipekm** [comment]
Yeah right @zenorocha, here the answers:

1. You're right, we don't need it;
3. Just habit, not necessary; 

I will handle all that very soon, thanks for your thoughts on this 👍

**Comment by zenorocha** [comment]
Awesome! I just sent an email to the guy that owns the Dracula name on Brackets registry. Let's see how it goes :)

**Comment by felipekm** [comment]
Great, I've just finished! :shipit: 

Here is the updated version with the official name:

image

**Comment by zenorocha** [comment]
🎉🎉🎉🎉

**Comment by zenorocha** [comment]
I'm going to make the changes on the website now

**Comment by zenorocha** [comment]
https://draculatheme.com/brackets

https://github.com/dracula/dracula.github.io/commit/f8eb910b1b6d800db28fe2eaa9b3bdfbba8b883a

https://github.com/dracula/brackets/commit/f1f9b1f312763f65ccdece6a779e15f2c4a4b311

**Comment by zenorocha** [comment]
By the way, I liked what you did with the screenshot, those two open panels were pretty nice. But I'm following the pattern of using the code samples (https://github.com/dracula/dracula-theme/issues/193) and one unique file showing. I hope in the future we can have a website with more screenshots for each app.

**Comment by felipekm** [comment]
Yeah sure, I got that. No worries :)

**Pull request merged**
